- build.gradle
- src/main/java/meshIneBits/Layer.java
- src/main/java/meshIneBits/Mesh.java
- src/main/java/meshIneBits/Pavement.java
- src/main/java/meshIneBits/config/WorkspaceConfig.java
- src/main/java/meshIneBits/config/patternParameter/DoubleParam.java
- src/main/java/meshIneBits/config/patternParameter/PatternParameter.java
- src/main/java/meshIneBits/gui/MainController.java
- src/main/java/meshIneBits/gui/utilities/.gitignore
- src/main/java/meshIneBits/gui/utilities/patternParamRenderer/LabeledSpinner.java
- src/main/java/meshIneBits/gui/view2d/Controller.java
- src/main/java/meshIneBits/gui/view2d/Core.java
- src/main/java/meshIneBits/gui/view2d/Wrapper.java
- src/main/java/meshIneBits/util/AreaTool.java
- src/main/java/meshIneBits/util/DetectorTool.java
- src/main/java/meshIneBits/util/Polygon.java
- src/main/java/meshIneBits/util/Segment2D.java
- src/main/java/meshIneBits/util/Vector2.java
* Close #53. Orientate bit with middle mouse.
* Close #54. Automatic cut.
* Delete selected bits when pressing Del.
> Enhancement for 2D view

- src/main/java/meshIneBits/Layer.java
- src/main/java/meshIneBits/Mesh.java
- src/main/java/meshIneBits/Model.java
- src/main/java/meshIneBits/config/WorkspaceConfig.java
- src/main/java/meshIneBits/gui/utilities/UPPNewBit.java
- src/main/java/meshIneBits/gui/view2d/BitPropertyPanel.java
- src/main/java/meshIneBits/gui/view2d/BitsPropertyPanel.java
- src/main/java/meshIneBits/gui/view2d/LayerPropertyPanel.java
- src/main/java/meshIneBits/gui/view2d/MeshController.java
- src/main/java/meshIneBits/gui/view2d/MeshPropertyPanel.java
- src/main/java/meshIneBits/gui/view2d/MeshWindow.java
- src/main/java/meshIneBits/gui/view2d/MeshWindowCore.java
- src/main/java/meshIneBits/gui/view2d/MeshWindowPropertyPanel.java
- src/main/java/meshIneBits/gui/view2d/MeshWindowSelector.java
- src/main/java/meshIneBits/gui/view2d/MeshWindowZoomer.java
- src/main/java/meshIneBits/gui/view2d/PropertyPanel.java
- src/main/java/meshIneBits/gui/view2d/PropertyTableModel.java
* Bit bulk selection. Close #75 
* Property panel of Mesh, Layer and selected Bits. Close #76 
* Refain adding irregular bits. Close #68
> Neo UI enhancement

- src/main/java/meshIneBits/Bit2D.java
- src/main/java/meshIneBits/Bit3D.java
- src/main/java/meshIneBits/Layer.java
- src/main/java/meshIneBits/M.java
- src/main/java/meshIneBits/gui/view2d/BitsPropertyPanel.java
- src/main/java/meshIneBits/gui/view2d/MeshController.java
- src/main/java/meshIneBits/gui/view2d/MeshWindowCore.java
- src/main/java/meshIneBits/gui/view2d/MeshWindowPropertyPanel.java
- src/main/java/meshIneBits/patterntemplates/DiagonalHerringbonePattern.java
- src/main/java/meshIneBits/util/AreaTool.java
- src/main/java/meshIneBits/util/Polygon.java
* Add rotation based on layer's number for Diagonal Herringbone Pattern. Close #82 
* Upgrade notification system with map of tags and values. Close #86 
* Minor fix on Property Panel when removing bits.
> Enhancements

- src/main/java/meshIneBits/Mesh.java
- src/main/java/meshIneBits/config/CraftConfig.java
- src/main/java/meshIneBits/gui/view2d/BitPropertyPanel.java
- src/main/java/meshIneBits/gui/view2d/BitsPropertyPanel.java
- src/main/java/meshIneBits/gui/view2d/MeshWindow.java
- src/main/java/meshIneBits/gui/view2d/MeshWindowPropertyPanel.java
- src/main/java/meshIneBits/scheduler/AScheduler.java
- src/main/java/meshIneBits/scheduler/BasicScheduler.java
- src/main/java/meshIneBits/util/XmlTool.java
New feature:
- Add bit ordering process 
- Add plate, batch id and unique bit id
- Add display of bit scheduling items on 2D windows bit property
> Feature #10: Basic scheduling implementation + debug on 2D space. 

- src/main/java/meshIneBits/Bit3D.java
- src/main/java/meshIneBits/Layer.java
- src/main/java/meshIneBits/Mesh.java
- src/main/java/meshIneBits/Model.java
- src/main/java/meshIneBits/Pavement.java
- src/main/java/meshIneBits/gui/view2d/MeshController.java
- src/main/java/meshIneBits/gui/view2d/MeshWindow.java
- src/main/java/meshIneBits/gui/view2d/MeshWindowCore.java
- src/main/java/meshIneBits/util/AreaSerializableTool.java
- src/main/java/meshIneBits/util/AreaTool.java
- src/main/java/meshIneBits/util/HandlerRedoUndo.java
fix saving problem and introduce undo/redo
> Sauvegard+Undo/Redo

- README.md
Add Installation, IntelliJ IDEA, Configuration, Running on README.md file for the future users
> [Documentation] (README.md)  

- src/main/java/meshIneBits/patterntemplates/EconomicPattern.java
Remove   - bitsLengthSpace in line 256  to respect the chosen space between two bits.
> [Fix Issue] (EconomicPattern.java)

- src/main/java/meshIneBits/gui/utilities/AboutDialogWindow.java
Update Name of developers on the About Window
> [UPDATE] (AboutDialogWindow.java)

- src/main/java/meshIneBits/gui/utilities/AboutDialogWindow.java
+ © --> (C)  in AboutDialogWindow.java  (because there was an odd character) right before
> [Fix] AboutDialogWindow.java

- src/main/java/meshIneBits/gui/view2d/MeshWindow.java
Resolve the problem about the Property Panel
> [Fix] MeshWindow

- src/main/java/meshIneBits/gui/view3d/ProcessingModelView.java
Commit 1: Change size for the components of the 3d View + the positions is adapted to the window size
Commit 2: Relative Rotation and position
Commit 3: 3d View initial window size is now more and less full screen ( more and less to permit user to easily reduce the windows size).
> Enhancement/3d view  (ProcessingModelView)

- src/main/java/meshIneBits/gui/view3d/ProcessingModelView.java
Correction Bug camera Center and Apply Gravity.
Now when reset the model is still visible
> [BUG+ENHANCEMENT] (ProcessingModelView)

- src/main/java/meshIneBits/gui/view3d/ProcessingModelView.java
Text that explain all possible shortcut on the 3D View
> [ENHANCEMENT] (ProcessingModelView)  Shortcut explanation

- src/main/java/meshIneBits/gui/view3d/ProcessingModelView.java
Removing ApplyScale Butoon and its function
> [REMOVE] (ProcessingModelView) ApplyScale Button

- src/main/java/meshIneBits/gui/view3d/ProcessingModelView.java
Change the mesh color when it is sliced.
+ add Text which is show when Mesh isSliced that say "The Model is Sliced
You can't rotate
You can't scale"
> [ENHANCEMENT] (ProcessingModelView) Change color when isSliced + text

- src/main/java/meshIneBits/gui/view2d/MeshWindow.java
- src/main/java/meshIneBits/gui/view2d/MeshWindowSelector.java
Fix bug of Components used in the 2D View interface when resizing window
1)Status bar
2)Zoomer
3)PropertyPanel
4)SelectorLayer
> [FIX] (View2D)  2D View interface

- src/main/java/meshIneBits/gui/view3d/ProcessingModelView.java
Fix a bug of Apply Button when mesh is sliced.
> [FIX] (ProcessingModelView) Apply

- src/main/java/meshIneBits/Pavement.java
Serialize Pavement to be able to save and open a paved project
> [FIX] (Pavement)  Serialize Pavement

- src/main/java/meshIneBits/gui/view2d/MeshWindow.java
Close Project properly.
Ask the user if he want to save the open project before closing or opening a new one.
> [FIX+ENHANCEMENT] (MeshWindow)  Close Project

- src/main/java/meshIneBits/util/supportExportFile/MeshXMLTool.java
Add safetySpace in condition for moving workingSpacePosition
> [Enhancement] Move-Working-Space

- src/main/java/meshIneBits/Bit3D.java
- src/main/java/meshIneBits/config/CraftConfig.java
- src/main/java/meshIneBits/util/supportExportFile/MeshXMLTool.java
Add CraftConfig Parameter
Change the referentiel to machine referentiel
> Feature/xml    Change referentiel + Add parameter

- src/main/java/meshIneBits/config/CraftConfig.java
- src/main/java/meshIneBits/gui/view3d/ProcessingModelView.java
Now in the animation we can see the Working Space
> Feature/3DView   Animation WorkingSpace
